### ISSUE TITLE
Problem with 'Switch an app off'

### ISSUE THREAD

**Issue by Davidslv** [alphagov/govuk-developer-docs#265]
Problem with 'Switch an app off' (https://docs.publishing.service.gov.uk/manual/howto-switch-off-app.html)

```
$ fab integration node_type:frontend puppet.disable
[localhost] Executing task 'node_type'
Disconnecting from [box]... done.
[box] Executing task 'puppet.disable'
Traceback (most recent call last):
  File "/Users/davidsilva/venv/fabric-scripts/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/Users/davidsilva/venv/fabric-scripts/lib/python2.7/site-packages/fabric/tasks.py", line 368, in execute
    multiprocessing
  File "/Users/davidsilva/venv/fabric-scripts/lib/python2.7/site-packages/fabric/tasks.py", line 264, in _execute
    return task.run(*args, **kwargs)
  File "/Users/davidsilva/venv/fabric-scripts/lib/python2.7/site-packages/fabric/tasks.py", line 171, in run
    return self.wrapped(*args, **kwargs)
TypeError: disable() takes exactly 1 argument (0 given)
```

**Comment by Davidslv** [comment]
Solved by #266
