### ISSUE TITLE
Deployment broken

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-developer-docs#4865]
Last successful run: https://github.com/alphagov/govuk-developer-docs/actions/runs/11499000463
October 24th, 1:11pm

First bad run: https://github.com/alphagov/govuk-developer-docs/actions/runs/11500022582/job/32009292992
October 24th, 2:17pm

```
I, [2024-10-24T13:17:02.286597 #2071]  INFO -- response: Status 200
/home/runner/work/govuk-developer-docs/govuk-developer-docs/app/github_repo_fetcher.rb:22:in `repo': alphagov/govuk-mobile-remote-config not found (RuntimeError)
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/app/github_repo_fetcher.rb:40:in `docs'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/app/proxy_pages.rb:13:in `block in repo_docs'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/app/proxy_pages.rb:12:in `map'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/app/proxy_pages.rb:12:in `repo_docs'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/app/proxy_pages.rb:3:in `resources'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/config.rb:56:in `evaluate_configuration!'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/gems/middleman-core-4.5.0/lib/middleman-core/application.rb:329:in `instance_eval'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/gems/middleman-core-4.5.0/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/gems/middleman-core-4.5.0/lib/middleman-core/application.rb:286:in `initialize'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/gems/middleman-cli-4.5.0/bin/middleman:49:in `new'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/gems/middleman-cli-4.5.0/bin/middleman:49:in `<top (required)>'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/bin/middleman:25:in `load'
	from /home/runner/work/govuk-developer-docs/govuk-developer-docs/vendor/bundle/ruby/3.3.0/bin/middleman:25:in `<main>'
```

We need to fix that, but also set up monitoring so that deploys don't silently fail...!

**Comment by ChrisBAshton** [comment]
Awesome, thanks @AgaDufrat!

Any thoughts on this? I'm happy to have a go at copying what we've done in govuk-rota-generator:

>  set up monitoring so that deploys don't silently fail...

**Comment by AgaDufrat** [comment]
That would be nice. We looked into notifications for failed GitHub Action runs https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/notifications-for-workflow-runs but the options are limited.
